SPORT_ATHLETICS = ("sport", "athletics")
FITNESS_CENTRE = ("leisure", "fitness_centre")

osmTagsForTheme: dict[str, list[tuple[str, str]]] = {
    "BOS_ZIELEN_POMNIKI_NEW": [("denotation", "natural_monument")],
    "BOS_ZIELEN_POMNIKI_SM_NEW": [("denotation", "natural_monument")],
    "I_PLACE_ZABAW_POINT": [("leisure", "playground")],
    "I_TOALETY": [("amenity", "toilets")],
    "K_ZTM_BILETOMATY_STACJONARNE": [("vending", "public_transport_tickets")],
    "ROWERY_STOJAKI_ROWEROWE": [("amenity", "bicycle_parking")],
    "S_BIEZNIE": [("leisure", "track")],
    "S_FITNESS": [FITNESS_CENTRE],
    "S_HALE_SPORTOWE": [("leisure", "sports_hall")],
    "S_KORTY_TENISOWE": [("sport", "tennis")],
    "S_KOSZYKOWKA": [("leisure", "pitch")],
    "S_KREGIELNIE": [("sport", "9pin")],
    "S_LODOWISKA": [("sport", "ice_skating")],
    "S_PILKA_NOZNA": [("sport", "soccer")],
    "S_PILKA_RECZNA": [("sport", "handball")],
    "S_PLYWALNIE_KRYTE": [("leisure", "swimming_pool")],
    "S_PLYWALNIE_ODKRYTE": [("leisure", "swimming_pool")],
    "S_SALE_GIMNASTYCZNE": [("sport", "gymnastics")],
    "S_SCIANKI_WSPINACZKOWE": [("sport", "climbing")],
    "S_SIATKOWKA": [("sport", "volleyball")],
    "S_SILOWNIE": [FITNESS_CENTRE],
    "S_SILOWNIE_PLENEROWE": [FITNESS_CENTRE],
    "S_SKATEPARKI": [("sport", "skateboard")],
    "S_SKOKI_W_DAL": [SPORT_ATHLETICS],
    "S_SKOKI_WZWYZ": [SPORT_ATHLETICS],
    "S_SPORTY_LODZIOWE": [("sport", "sailing")],
    "S_SQUASH": [("sport", "squash")],
    "S_STADIONY_LA": [SPORT_ATHLETICS],
    "S_STRZELNICE": [("sport", "shooting")],
}
